sudo: required
services:
  - docker
language: jvm
jdk: openjdk8
env:
  global:
    secure: cq3fOlV8Ooa16hWyPXSTapkyJDROb1dI/OP70R5MSoMWsPQucFeL0RyPzsLelqY9GV80t/IUhxhAmKKpZLw40Bus2dmPjmAlGNHwnCD6Q375ebzKqK1I6FFX4dydcDdrM4UEa9zgNX25ljejl+esKzktIufqjnCUNw0wDtYr285BdShPcsH6Oa5zfXGUriCvtfxgBOzIdplQBXy/U7k6+8COLdYEg+ybntZHlNlqQVzquQLOod2ZUPeedpHiR/kT1TaovQ+ySaZxel2WJk/F4rFILzkcREiJX10m3ramO7yt29K3GktafhxtFYWGW0Xa7RhMMguKyDCE5wMPZCswqfZ19ZMVO1so+T0pOvhJQLw6ROTVPARLok7FQt9S4RrMk7//8sFglb+5aYg6UWlaiCB/BiqwPsfAOwUxdUemQCZ4MvOYR8gK4AZ2zDn2TIafAtnqN5hV0O6cBF1XP2XkKVcnAloSujI8dkhDYcx8vkPCLJm3aT2CbGdTx9iBtGrzUIUjCWUZYvZywz7JNcQkM6qXaelytof4/XVX9Bup10yKL0WSmU+AZugoAUkpy1BboiDoaCKnyNkJxjYucSrmK6G6q8E44xdybPeYFy8q6wDGAdRhax3JZ8OIKhJ+ZCTtKreTnpdM7BxhiuuBOtWQWpI+EbCSxbIX2PjICLq+lNw=
node_js: lts/*
install: true
addons:
  apt:
    packages:
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - jq
      - unzip
      - docker-ce
      - python-pip
before_install:
  - sudo pip install docker-compose httpie >/dev/null 2>&1
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080 8082 9092
  - sudo service mysql stop
script:
  - ./mvnw -DskipTests >/dev/null
  - ./mvnw
  #
  - ./mvnw -f docker/h2/pom.xml -P up
  - bash ./apps/h2-eventstore/target/*.jar &
  - wait_for 8080
  - http :8080/auto | jq '.'
  - stop_any 8080
  - sleep 1s
cache:
  packages: true
  npm: true
  directories:
    - ~/.m2/
    - ~/.docker/
    - ./node_modules/
    - ~/.npm/
before_deploy:
  - npm i ; npm run gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ./.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
notifications:
  email: false
git:
  depth: false
  quiet: true
